### ISSUE TITLE
Refreshing

### ISSUE THREAD

**Issue by IMgoRt** [fredli74/fetch-tesla-token#1]
Hi,
I have a valid refresh token, how would I subsequently execute your code using the refresh_token rather than starting from email/password?

Thanks

**Comment by fredli74** [comment]
There's no built-in function for refreshing a token in the HTML page. But if you run it locally with node.js it's super easy making your own, just using the cleaned-up teslaAuth.js library I added in the latest commit.

Clone or download the repository. Then create a `refresh.js` file in the root (next to the `teslaAuth.js` file), just containing something like this.

```javascript

const teslaAuth = require("./teslaAuth");

const token = teslaAuth
    .refreshToken("<<<YOUR REFRESH TOKEN>>>")
    .then(t => console.log(t))
```

Run it with  `node refresh.js`

The refresh call is a simple POST to the Tesla server. You can just curl it if you like.

```bash
curl --header "Content-Type: application/json" --data '{
 "grant_type":"refresh_token",
 "scope":"openid email offline_access",
 "client_id":"ownerapi",
 "refresh_token":"<<<YOUR REFRESH TOKEN>>>"
}' https://auth.tesla.com/oauth2/v3/token
```

**Comment by fredli74** [comment]
The `teslaAuth.js` file is all you need from my repository if you want to put the function in your own project. Just copy that single file and then you can use the `authenticate`, `refreshToken`, and `ownerapiToken` functions. They're all documented inside the source.

https://github.com/fredli74/fetch-tesla-token/blob/5c3109849936e0035d26a57e71636969c5496b6d/teslaAuth.js#L102-L112

https://github.com/fredli74/fetch-tesla-token/blob/5c3109849936e0035d26a57e71636969c5496b6d/teslaAuth.js#L273-L279

https://github.com/fredli74/fetch-tesla-token/blob/5c3109849936e0035d26a57e71636969c5496b6d/teslaAuth.js#L294-L300

**Comment by IMgoRt** [comment]
> The `teslaAuth.js` file is all you need from my repository if you want to put the function in your own project. Just copy that single file and then you can use the `authenticate`, `refreshToken`, and `ownerapiToken` functions. They're all documented inside the source.
> 
> https://github.com/fredli74/fetch-tesla-token/blob/5c3109849936e0035d26a57e71636969c5496b6d/teslaAuth.js#L102-L112
> 
> https://github.com/fredli74/fetch-tesla-token/blob/5c3109849936e0035d26a57e71636969c5496b6d/teslaAuth.js#L273-L279
> 
> https://github.com/fredli74/fetch-tesla-token/blob/5c3109849936e0035d26a57e71636969c5496b6d/teslaAuth.js#L294-L300

That's great, thanks for taking the time to reply, I'll try it out in the morning (01:11 here)
