### ISSUE TITLE
Error fetching Tesla sign in page !

### ISSUE THREAD

**Issue by dranreb38** [fredli74/fetch-tesla-token#2]
Hello,
After entering my login and password and the MFA code it does not work!
![Screenshot_72](https://user-images.githubusercontent.com/16446911/120502419-b274c180-c3c2-11eb-92ec-f3a55491765c.png)

**Comment by dranreb38** [comment]
![Screenshot_73](https://user-images.githubusercontent.com/16446911/120503171-59595d80-c3c3-11eb-82a7-d05dd5097e5f.png)

**Comment by fredli74** [comment]
Oh, I see that matchAll was added in node.js version 12. Are you running an older node by any chance?

```node --version```

**Comment by dranreb38** [comment]
Node --Version 
v10.24.0
Upgrade in 12 -> 
`curl -sL https://deb.nodesource.com/setup_12.x | bash -apt-get install -y nodejs `

**Comment by dranreb38** [comment]
It's **OK** with NodeJs 12.22.1 
Thank
