### ISSUE TITLE
Does not work anymore !

### ISSUE THREAD

**Issue by dranreb38** [fredli74/fetch-tesla-token#4]
Hello,
I'm trying to relaunch my fetch-token-token, but it doesn't work anymore. After validating my login and password, the authenticate button no longer has any effect, I no longer have the MFA authentication. Is this due to a new modification of tesla?

**Comment by fredli74** [comment]
Are you running the latest version? I had to make changes at the end of July because they implemented captcha.

**Comment by fredli74** [comment]
Crap, they have replaced the captcha solution with a JavaScript-based ReCaptcha. The old solution of forwarding the captcha image and sending the result with the form will not work anymore. At the moment I have no clue how to solve that.

**Comment by dranreb38** [comment]
Crap !  :(
And yes I am using the latest version! (pull 9816a34 on 28 Jul 2021)

**Comment by dranreb38** [comment]
news ?

**Comment by fredli74** [comment]
Was experimenting with this yesterday. I can make a version that redirects you to Teslas login page to avoid all problems. But that solution would require you to then manually copy the redirect url to fetch the tokens.

Better than nothing I suppose.
